### ISSUE TITLE
Pin to use specific version of official AWS tf modules

### ISSUE THREAD

**Issue by alexis-renard** [jasonwalsh/terraform-aws-boundary#6]
The fact that the version of the official modules are not fixed by default is now an issue.

For instance, for the /modules/boundary, the terraform-aws-modules/autoscaling/aws module version isn't fixed and so the following error is displayed : 

```terraform
Error: Unsupported argument

    on modules/aws-boundary/modules/boundary/main.tf line 47, in module "autoscaling":
    47:   iam_instance_profile        = var.iam_instance_profile

An argument named "iam_instance_profile" is not expected here.

Error: Unsupported argument

    on modules/aws-boundary/modules/boundary/main.tf line 54, in module "autoscaling":
    54:   recreate_asg_when_lc_changes = true

An argument named "recreate_asg_when_lc_changes" is not expected here.
```

Same issue with the `module "alb"`, `module "postgresql"` and `module "vpc"`. 

Do you have in mind the versions that has been initially used so that we can pin them. 

Next step update the code to call the latest version of these official modules.

**Comment by alexis-renard** [comment]
@ptavares if you want to follow this one :)

**Comment by jasonwalsh** [comment]
@alexis-renard see #7 for the proposed changes
