### ISSUE TITLE
Error: "name_prefix" can only alphanumeric characters and ()./_- symbols

### ISSUE THREAD

**Issue by inkicthus** [jasonwalsh/terraform-aws-boundary#8]
I've tried running this from both Windows (PowerShell) and Linux. I consistently get the same error.
![image](https://user-images.githubusercontent.com/19429716/137158610-f2bf164b-51ed-4b50-bcda-a2d6e7c28c19.png)

I'm far from a Terraform expert, but I cannot see anything that looks wrong in that file. I've tried to investigate those variables, but it doesn't shed any light...
```
terraform console
> local.lt_name
(known after apply)
> var.name
(known after apply)
```

I captured debug logs and I see a lot of two different types of messages:

- `[INFO]  ReferenceTransformer: reference not found: "<xxxx>"` 
- `[WARN]  Provider "<yyyy>" produced an invalid plan for <zzzz>, but we are tolerating it because it is using the legacy plugin SDK.`

The actual names for x, y, and z change, but those messages pop up a lot. Not sure if that means more to anyone else than it does to me, but those two messages account for 90% of the log.

**Comment by jasonwalsh** [comment]
Thank you for creating this issue. I will work on a fix.
